<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useSessionStore } from '@/stores/session'
const session = useSessionStore(); const url = ref(''); const username = ref(''); const password = ref(''); const busy = ref(false); const error = ref('')
onMounted(async () => { await session.hydrate(); if (session.connected) uni.switchTab({ url: '/pages/dashboard/index' }) })
async function submit() { if (!url.value.trim()) { error.value = '请输入服务器地址'; return }; busy.value = true; error.value = ''; try { await session.connectToServer(url.value, username.value.trim(), password.value); uni.switchTab({ url: '/pages/dashboard/index' }) } catch (cause) { error.value = `连接失败：${cause instanceof Error ? cause.message : '网络不可用'}` } finally { busy.value = false } }
</script>
<template><view class="login safe-area"><view class="brand"><view class="mark">→</view><text class="name">Ejunz Edge</text><text class="subtitle">连接 Edge 服务器，管理远程节点与设备</text></view><view class="card"><text class="card-title">连接服务器</text><text class="hint">支持局域网地址或远程 HTTPS 地址</text><input v-model="url" class="input" type="text" placeholder="http://192.168.1.100:5283" confirm-type="next" /><input v-model="username" class="input" type="text" placeholder="用户名（可选）" confirm-type="next" /><input v-model="password" class="input" type="password" placeholder="密码（可选）" confirm-type="done" @confirm="submit" /><button class="primary" :disabled="busy" @tap="submit">{{ busy ? '连接中…' : '连接 Edge' }}</button><text v-if="error" class="error">{{ error }}</text></view><text class="footer">凭据仅保存在本机安全存储中</text></view></template>
<style scoped>.login { min-height:100vh; padding:150rpx 42rpx 70rpx; background:radial-gradient(circle at 50% -10%, #173b55 0, #08111f 54%); }.brand { text-align:center; margin-bottom:70rpx; }.mark { display:flex; align-items:center; justify-content:center; width:110rpx; height:110rpx; margin:0 auto 28rpx; border:2rpx solid #55d6be; border-radius:34rpx; color:#55d6be; font-size:70rpx; font-weight:800; }.name { display:block; font-size:54rpx; font-weight:800; }.subtitle { display:block; color:#75809a; font-size:24rpx; margin-top:16rpx; }.card { background:#101a2d; border:1rpx solid #1a2a43; border-radius:30rpx; padding:38rpx 32rpx; box-shadow:0 24rpx 70rpx rgba(0,0,0,.22); }.card-title { display:block; font-size:34rpx; font-weight:800; }.hint { display:block; color:#75809a; font-size:22rpx; margin:12rpx 0 30rpx; }.input { height:92rpx; padding:0 24rpx; color:#edf5ff; background:#08111f; border:1rpx solid #243754; border-radius:16rpx; margin-bottom:18rpx; font-size:27rpx; }.primary { height:92rpx; line-height:92rpx; background:#55d6be; color:#08111f; border-radius:16rpx; font-size:29rpx; font-weight:800; margin-top:10rpx; }.primary[disabled] { opacity:.55; }.error { display:block; color:#ff6b7a; text-align:center; font-size:23rpx; margin-top:22rpx; }.footer { display:block; text-align:center; color:#4f607b; font-size:21rpx; margin-top:32rpx; }</style>
