<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import AppShell from '@/components/AppShell.vue'; import PageHeader from '@/components/PageHeader.vue'; import { fetchAuthConfig, fetchUpstreamConfig, restartUpstream, updateAuthConfig, updateUpstreamConfig } from '@/services/api'; import type { AuthConfig, UpstreamConfig } from '@/types/edge'
const auth = reactive<AuthConfig>({ enabled:false, username:'', passwordConfigured:false }); const upstream = reactive<UpstreamConfig>({ enabled:false, endpoint:'', connected:false }); const authPassword = ref(''); const upstreamToken = ref(''); const saving = ref(''); const notice = ref('')
async function refresh() { try { const [a, u] = await Promise.all([fetchAuthConfig(), fetchUpstreamConfig()]); Object.assign(auth, a); Object.assign(upstream, u); notice.value = '' } catch (cause) { notice.value = cause instanceof Error ? cause.message : '加载失败' } }
async function saveAuth() { saving.value = 'auth'; try { await updateAuthConfig({ enabled:auth.enabled, username:auth.username, ...(authPassword.value ? { password:authPassword.value } : {}) }); authPassword.value=''; notice.value='认证配置已保存'; await refresh() } catch (cause) { notice.value = cause instanceof Error ? cause.message : '保存失败' } finally { saving.value='' } }
async function saveUpstream() { saving.value='upstream'; try { await updateUpstreamConfig({ enabled:upstream.enabled, endpoint:upstream.endpoint, ...(upstreamToken.value ? { token:upstreamToken.value } : {}) }); upstreamToken.value=''; notice.value='上游配置已保存'; await refresh() } catch (cause) { notice.value = cause instanceof Error ? cause.message : '保存失败' } finally { saving.value='' } }
async function restart() { saving.value='restart'; try { await restartUpstream(); notice.value='上游连接已重启'; setTimeout(refresh, 1500) } catch (cause) { notice.value = cause instanceof Error ? cause.message : '重启失败' } finally { saving.value='' } }
function switchValue(event: Event): boolean { return Boolean((event as unknown as { detail?: { value?: boolean } }).detail?.value) }
function onAuthToggle(event: Event) { auth.enabled = switchValue(event) }
function onUpstreamToggle(event: Event) { upstream.enabled = switchValue(event) }
onMounted(refresh)
</script>
<template><AppShell><template #title>设置</template><PageHeader title="服务器设置" :refreshing="saving !== ''" @refresh="refresh" /><text v-if="notice" class="notice">{{ notice }}</text><view class="card"><text class="card-title">Edge 认证</text><view class="row"><text>启用认证</text><switch :checked="auth.enabled" color="#55d6be" @change="onAuthToggle" /></view><input v-model="auth.username" class="input" placeholder="用户名" /><input v-model="authPassword" class="input" type="password" :placeholder="auth.passwordConfigured ? '新密码（留空不变）' : '密码'" /><button class="primary" :disabled="saving === 'auth'" @tap="saveAuth">{{ saving === 'auth' ? '保存中…' : '保存认证' }}</button></view><view class="card"><text class="card-title">Upstream 级联</text><view class="row"><text>启用上游</text><switch :checked="upstream.enabled" color="#55d6be" @change="onUpstreamToggle" /></view><input v-model="upstream.endpoint" class="input" placeholder="ws://upstream:5283/node/conn" /><input v-model="upstreamToken" class="input" type="password" placeholder="Token（留空不变）" /><view class="connection"><text>当前连接</text><text :class="upstream.connected ? 'good' : 'warn'">{{ upstream.connected ? '已连接' : '未连接' }}</text></view><view class="buttons"><button class="primary" :disabled="saving === 'upstream'" @tap="saveUpstream">保存配置</button><button class="secondary" :disabled="saving === 'restart'" @tap="restart">{{ saving === 'restart' ? '重启中…' : '重启连接' }}</button></view></view></AppShell></template>
<style scoped>.notice { display:block; color:#55d6be; font-size:22rpx; background:#55d6be16; border-radius:14rpx; padding:18rpx; margin-bottom:20rpx; }.card { background:#101a2d; border:1rpx solid #1a2a43; border-radius:24rpx; padding:28rpx; margin-bottom:20rpx; }.card-title { display:block; font-weight:800; font-size:29rpx; margin-bottom:22rpx; }.row,.connection { display:flex; justify-content:space-between; align-items:center; color:#edf5ff; font-size:24rpx; margin-bottom:18rpx; }.input { width:100%; height:82rpx; padding:0 20rpx; color:#edf5ff; background:#08111f; border:1rpx solid #243754; border-radius:14rpx; margin-bottom:16rpx; }.primary,.secondary { flex:1; height:78rpx; line-height:78rpx; border-radius:14rpx; font-size:24rpx; font-weight:700; }.primary { background:#55d6be; color:#08111f; }.secondary { background:#243754; color:#edf5ff; }.buttons { display:flex; gap:14rpx; }.good { color:#55d6be; }.warn { color:#ffbd69; }</style>
