<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'; import AppShell from '@/components/AppShell.vue'; import PageHeader from '@/components/PageHeader.vue'; import EmptyState from '@/components/EmptyState.vue'; import DeviceSwitch from '@/components/DeviceSwitch.vue'; import { useEdgeStore } from '@/stores/edge'; import { edgeWs, edgeWsState, subscribeDeviceStates } from '@/services/edge-ws'; import { onlineNodes } from '@/utils/status'
const edge = useEdgeStore(); const toggling = ref(new Set<string>()); let unsubscribe: (() => void) | undefined; let unsubscribeSnapshot: (() => void) | undefined; let timer: ReturnType<typeof setInterval> | undefined
async function refreshNodes() { try { await edge.refresh(); if (!edge.selectedNodeId && onlineNodes(edge.nodes).length) await edge.selectNode(onlineNodes(edge.nodes)[0].nodeId) } catch {} }; async function choose(nodeId: string) { await edge.selectNode(nodeId) }; async function toggle(device: any) { if (toggling.value.has(device.deviceId)) return; toggling.value = new Set(toggling.value).add(device.deviceId); try { await edge.toggleDevice(device) } catch {} finally { const next = new Set(toggling.value); next.delete(device.deviceId); toggling.value = next } }
watch(() => edge.selectedNodeId, () => {
  unsubscribe?.(); unsubscribeSnapshot?.()
  const nodeIds = edge.selectedNodeId ? [edge.selectedNodeId] : undefined
  unsubscribe = subscribeDeviceStates((message) => edge.applyDeviceState(message.topic, message.payload, message.nodeId, message.deviceId), { nodeIds })
  unsubscribeSnapshot = edgeWs.subscribeSnapshots((snapshot) => {
    for (const node of snapshot.nodes || []) {
      if (edge.selectedNodeId && node.nodeId !== edge.selectedNodeId) continue
      for (const [deviceId, payload] of Object.entries(node.deviceStates || {})) {
        edge.applyDeviceState(`node/${node.nodeId}/devices/${deviceId}/state`, payload, node.nodeId, deviceId)
      }
    }
  })
  edgeWs.setSubscription({ nodeIds })
}, { immediate: true }); onMounted(() => { refreshNodes(); timer = setInterval(refreshNodes, 5000) }); onUnmounted(() => { unsubscribe?.(); unsubscribeSnapshot?.(); if (timer) clearInterval(timer) })
</script>
<template><AppShell><template #title>设备</template><PageHeader title="设备控制" :refreshing="edge.devicesLoading" @refresh="edge.refreshDevices" /><view class="ws"><view class="pulse" :class="edgeWsState.status" /><text>{{ edgeWsState.status === 'connected' ? '实时同步已连接' : edgeWsState.status === 'connecting' ? '实时同步连接中' : '实时同步未连接' }}</text></view><picker class="picker" mode="selector" :range="onlineNodes(edge.nodes)" range-key="nodeId" @change="choose(onlineNodes(edge.nodes)[Number($event.detail.value)]?.nodeId)"><view class="picker-inner">{{ edge.selectedNodeId || '选择在线节点' }} <text>⌄</text></view></picker><EmptyState v-if="!edge.selectedNodeId" text="请选择一个在线节点" /><EmptyState v-else-if="!edge.devices.length && !edge.devicesLoading" text="该节点暂无设备" /><view v-else class="list"><view v-for="device in edge.devices" :key="device.deviceId" class="device"><view class="main"><text class="name">{{ device.friendlyName }}</text><text class="meta">{{ device.deviceId }}{{ device.model ? ` · ${device.model}` : '' }}</text></view><DeviceSwitch v-if="device.supportsOnOff !== false" :checked="device.currentState === 'ON'" :disabled="toggling.has(device.deviceId)" @change="toggle(device)" /></view></view></AppShell></template>
<style scoped>.ws { display:flex; align-items:center; gap:12rpx; color:#75809a; font-size:21rpx; margin-bottom:18rpx; }.pulse { width:14rpx; height:14rpx; border-radius:50%; background:#ff6b7a; }.pulse.connected { background:#55d6be; }.pulse.connecting { background:#ffbd69; }.picker { display:block; margin-bottom:24rpx; }.picker-inner { display:flex; justify-content:space-between; color:#edf5ff; background:#101a2d; border:1rpx solid #1a2a43; border-radius:16rpx; padding:25rpx; }.picker-inner text { color:#55d6be; }.list { display:flex; flex-direction:column; gap:16rpx; }.device { display:flex; align-items:center; justify-content:space-between; gap:20rpx; background:#101a2d; border:1rpx solid #1a2a43; border-radius:22rpx; padding:26rpx; }.main { min-width:0; display:flex; flex-direction:column; gap:9rpx; }.name { font-size:27rpx; font-weight:700; }.meta { color:#75809a; font-size:20rpx; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }</style>
